version: '3.1'
services:
  jiduoduo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'jiduoduo-webserver'
    ports:
      - ${WEBSERVER:-15000}:5000
    working_dir: /jiduoduo_data
    volumes:
      - ./jiduoduo_data:/jiduoduo_data
    restart: always
    command: [
      'gunicorn',
      '--log-level=INFO',
      '--capture-output',
      '--access-logfile','-',
      '--error-logfile', '-',
      '-b', '0.0.0.0:5000',
      '-k', 'gevent',
      '-w', '2',
      '-t', '30',
      'jiduoduo.app:app'
    ]
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"

# docker-compose pull

# docker-compose build

# docker-compose down && docker-compose up -d
