# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import nezha_pb2 as nezha__pb2

GRPC_GENERATED_VERSION = '1.65.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in nezha_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class NezhaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportSystemState = channel.unary_unary(
                '/proto.NezhaService/ReportSystemState',
                request_serializer=nezha__pb2.State.SerializeToString,
                response_deserializer=nezha__pb2.Receipt.FromString,
                _registered_method=True)
        self.ReportSystemInfo = channel.unary_unary(
                '/proto.NezhaService/ReportSystemInfo',
                request_serializer=nezha__pb2.Host.SerializeToString,
                response_deserializer=nezha__pb2.Receipt.FromString,
                _registered_method=True)
        self.ReportTask = channel.unary_unary(
                '/proto.NezhaService/ReportTask',
                request_serializer=nezha__pb2.TaskResult.SerializeToString,
                response_deserializer=nezha__pb2.Receipt.FromString,
                _registered_method=True)
        self.RequestTask = channel.unary_stream(
                '/proto.NezhaService/RequestTask',
                request_serializer=nezha__pb2.Host.SerializeToString,
                response_deserializer=nezha__pb2.Task.FromString,
                _registered_method=True)
        self.IOStream = channel.stream_stream(
                '/proto.NezhaService/IOStream',
                request_serializer=nezha__pb2.IOStreamData.SerializeToString,
                response_deserializer=nezha__pb2.IOStreamData.FromString,
                _registered_method=True)
        self.LookupGeoIP = channel.unary_unary(
                '/proto.NezhaService/LookupGeoIP',
                request_serializer=nezha__pb2.GeoIP.SerializeToString,
                response_deserializer=nezha__pb2.GeoIP.FromString,
                _registered_method=True)


class NezhaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReportSystemState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportSystemInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IOStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LookupGeoIP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NezhaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportSystemState': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportSystemState,
                    request_deserializer=nezha__pb2.State.FromString,
                    response_serializer=nezha__pb2.Receipt.SerializeToString,
            ),
            'ReportSystemInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportSystemInfo,
                    request_deserializer=nezha__pb2.Host.FromString,
                    response_serializer=nezha__pb2.Receipt.SerializeToString,
            ),
            'ReportTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTask,
                    request_deserializer=nezha__pb2.TaskResult.FromString,
                    response_serializer=nezha__pb2.Receipt.SerializeToString,
            ),
            'RequestTask': grpc.unary_stream_rpc_method_handler(
                    servicer.RequestTask,
                    request_deserializer=nezha__pb2.Host.FromString,
                    response_serializer=nezha__pb2.Task.SerializeToString,
            ),
            'IOStream': grpc.stream_stream_rpc_method_handler(
                    servicer.IOStream,
                    request_deserializer=nezha__pb2.IOStreamData.FromString,
                    response_serializer=nezha__pb2.IOStreamData.SerializeToString,
            ),
            'LookupGeoIP': grpc.unary_unary_rpc_method_handler(
                    servicer.LookupGeoIP,
                    request_deserializer=nezha__pb2.GeoIP.FromString,
                    response_serializer=nezha__pb2.GeoIP.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.NezhaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.NezhaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NezhaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReportSystemState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.NezhaService/ReportSystemState',
            nezha__pb2.State.SerializeToString,
            nezha__pb2.Receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportSystemInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.NezhaService/ReportSystemInfo',
            nezha__pb2.Host.SerializeToString,
            nezha__pb2.Receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.NezhaService/ReportTask',
            nezha__pb2.TaskResult.SerializeToString,
            nezha__pb2.Receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/proto.NezhaService/RequestTask',
            nezha__pb2.Host.SerializeToString,
            nezha__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IOStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/proto.NezhaService/IOStream',
            nezha__pb2.IOStreamData.SerializeToString,
            nezha__pb2.IOStreamData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LookupGeoIP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.NezhaService/LookupGeoIP',
            nezha__pb2.GeoIP.SerializeToString,
            nezha__pb2.GeoIP.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
